name: exception_helper
description: "A new Flutter package project."
version: 0.0.1
homepage: " "

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"
 
dependencies:
  flutter:
    sdk: flutter

  firebase_auth:
  firebase_core:
  firebase_storage:
  cloud_firestore: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

